export const INTERESTS = [
  { id:"futbol",      label:"Fútbol",             icon:"⚽", group:"Deportes",   tm:"Football"       },
  { id:"basketball",  label:"Baloncesto",          icon:"🏀", group:"Deportes",   tm:"Basketball"     },
  { id:"beisbol",     label:"Béisbol",             icon:"⚾", group:"Deportes",   tm:"Baseball"       },
  { id:"tenis",       label:"Tenis",               icon:"🎾", group:"Deportes",   tm:"Tennis"         },
  { id:"ciclismo",    label:"Ciclismo",            icon:"🚴", group:"Deportes",   tm:"Cycling"        },
  { id:"natacion",    label:"Natación",            icon:"🏊", group:"Deportes",   tm:"Swimming"       },
  { id:"rock",        label:"Rock",                icon:"🎸", group:"Música",     tm:"Rock"           },
  { id:"pop",         label:"Pop",                 icon:"🎤", group:"Música",     tm:"Pop"            },
  { id:"electronica", label:"Electrónica",         icon:"🎧", group:"Música",     tm:"Electronic"     },
  { id:"reggaeton",   label:"Reggaetón",           icon:"🎵", group:"Música",     tm:"Reggaeton"      },
  { id:"clasica",     label:"Clásica",             icon:"🎻", group:"Música",     tm:"Classical"      },
  { id:"jazz",        label:"Jazz & Blues",        icon:"🎷", group:"Música",     tm:"Jazz"           },
  { id:"latina",      label:"Música Latina",       icon:"💃", group:"Música",     tm:"Latin"          },
  { id:"teatro",      label:"Teatro",              icon:"🎭", group:"Artes",      tm:"Theatre"        },
  { id:"danza",       label:"Danza",               icon:"🩰", group:"Artes",      tm:"Dance"          },
  { id:"comedia",     label:"Comedia",             icon:"😂", group:"Artes",      tm:"Comedy"         },
  { id:"arte",        label:"Arte y Exposiciones", icon:"🖼️", group:"Artes",     tm:"Arts & Theatre" },
  { id:"tech",        label:"Tecnología",          icon:"💻", group:"Tecnología", tm:"Technology"     },
  { id:"gaming",      label:"Gaming & Esports",    icon:"🎮", group:"Tecnología", tm:"Gaming"         },
  { id:"astronomia",  label:"Astronomía",          icon:"🔭", group:"Ciencia",    tm:"Science"        },
  { id:"naturaleza",  label:"Naturaleza",          icon:"🌿", group:"Ciencia",    tm:"Nature"         },
  { id:"familia",     label:"Familia",             icon:"👨‍👩‍👧", group:"Familia", tm:"Family"      },
  { id:"gastronomia", label:"Gastronomía",         icon:"🍽️", group:"Familia",   tm:"Food & Drink"   },
  { id:"moda",        label:"Moda & Lifestyle",    icon:"👗", group:"Familia",    tm:"Lifestyle"      },
];
export const INTEREST_GROUPS = [...new Set(INTERESTS.map(i => i.group))];
